name: release

on:
  push:
    tags:
      - 'github-agent/*'

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "TODO: Implement the release workflow"
