name: release

on:
  push:
    tags:
      - 'github-agent/*'

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      repo_access_token: ${{ steps.secrets.outputs.REPO_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Run build
      run: pnpm -r build
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      id: gauth
      with:
        token_format: access_token
        project_id: "dengenlabs"
        service_account: gar-pusher@dengenlabs.iam.gserviceaccount.com
        workload_identity_provider: "projects/265888598630/locations/global/workloadIdentityPools/composable-cloud/providers/github"
        access_token_lifetime: 300s
        create_credentials_file: true
    - name: Authenticate to Google Artifact Registry
      run: pnpm run artifactregistry-login --repo-config=.npmrc
    - name: Publish Package
      run: |
        # We modified the .npmrc file to use GAR, which put the Git repository in dirty state.
        # So we need to disable the Git checks.
        pnpm publish packages/github-agent --no-git-checks
    - name: Get Repository Access Token
      id: secrets
      run: |
        echo "REPO_ACCESS_TOKEN=$(gcloud secrets versions access latest --secret=github-repo-studio-access-token)" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Dispatch Deployment Request
        uses: myrotvorets/trigger-repository-dispatch-action@1.0.0
        with:
          token: ${{ needs.release.outputs.repo_access_token }}
          repo: becomposable/studio
          type: gcp-deployment-request
          payload: |
            {
              "environment": "staging",
              "sha": "${{ github.sha }}",
              "cloud_run_only": false
            }
